### ISSUE TITLE
Proper Look

### ISSUE THREAD

**Issue by sasalx** [Egomination/MangApplizer-Beta#2]
A proper design to the app.

- [x] Proper HTML structure
- [x] Fix for CSS
- [x] Design viewer
- [x] Design Downloader

**Comment by sasalx** [comment]
With #8 added _navbar_ and _tab system_.

**Comment by sasalx** [comment]
With #8 Manga Downloader has its own tab.

**Comment by sasalx** [comment]
- [x] Navbar support for smaller windows.

Added with #12

**Comment by sasalx** [comment]
Idea: 

- [x] Use carousel for viewer.

- [x] Toast for download button instead of new window.

**Comment by sasalx** [comment]
With #12 added a source select menu.

**Comment by sasalx** [comment]
With #18 toast is added.

**Comment by kondanta** [comment]
Pressing enter after filling the forms triggers the reset button

@sasalx 

Fixed with #23

**Comment by sasalx** [comment]
Viewer beta #23

**Comment by sasalx** [comment]
Viewer V2 #28

**Comment by sasalx** [comment]
Added prev - next button for viewer #36
