### ISSUE TITLE
Transition between Lsh and kissmanga

### ISSUE THREAD

**Issue by kondanta** [Egomination/MangApplizer-Beta#24]
### Expected Behaviour
We can download any source, anytime we want. 

### Actual Behaviour
After downloading kissmanga, we cannot switch other source(s).

### Steps to Reproduce
Download any available manga from kissmanga, then try to switch lhs.

**Comment by sasalx** [comment]
From what I gathered problem seems to be kissmanga. After downloading something from kissmanga jquery script doesnt works but if you download something from lhscans it does work.

**Comment by kondanta** [comment]
Things I found: It's mainly because of hakuneko. After hakuenko functions fired, the button become invalid, and jQuerry does not respond any changes. Also, after firing kissmanga function quick change of sources broke the next source as well.

**Possible solution**: Manual scrapping.

**Comment by kondanta** [comment]
It'll be fixed after the beta release.
