### ISSUE TITLE
Cached Urls

### ISSUE THREAD

**Issue by kondanta** [Egomination/MangApplizer-Beta#27]
without refreshing the app, lhscans download the cached urls from previous chapters then given chapter.
It's also because of the request module's issue.

**Comment by sasalx** [comment]
While testing every request call with `console.log(response.socket.destroyed);` it seems like function GetAvailableChapters in lhscan fails to give a response which means code cannot reach at that point. So I think that is why socket hangs up.

**Comment by kondanta** [comment]
GetAvailableChapters invoked when the given chapter is not found. It also returns true when it's invoked.

**Comment by kondanta** [comment]
*I solved it using response.socket.end(). Also reallocating list fixed the cached url problem*
