### ISSUE TITLE
DB Multi Table Fasshion

### ISSUE THREAD

**Issue by kondanta** [Egomination/MangApplizer-Beta#43]
# Issue
The main idea behind having database is separating multiple resources, so that handling them would be easier. However, having a dynamic query makes it inject-able.

# Possible Solutions
- Rollback to the Json.
- One huge table that contains multiple table's information

Name | Url | ExtraStuff
--- | --- | ---
Shokugeki no Souma - Raw  | manga-shokugeki-no-souma-raw.html | extra
Shokugeki no Soma | /Manga/Shokugeki-no-Soma | extra
**Possible 3rd source** | **that contains same /Manga/Shokugeki-no-Soma** | extra
   + Will probably cause another issue that, downloading from wrong source.

**Comment by sasalx** [comment]
Will be fixed with new version of the app.
